Added maven installation check

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -12,10 +12,20 @@ jobs:
         uses: actions/checkout@v7
         
       - name: setup jdk
-        uses: actions/setup-java@v6
+        uses: actions/setup-java@v4
         with:
           distribution: 'temurin'
           java-version: '17'
+          
+      - name: Ensure maven is installed
+        run : |
+           if ! command -v mvn &> /dev/null; then
+            echo "Maven not found. Installing..."
+            sudo dnf install -y maven
+             else
+               echo "Maven is already installed"
+             fi
+               mvn -version
           
       - name: Build with maven
         run: mvn clean package -DskipTests
